### ISSUE TITLE
What standard is the code following?

### ISSUE THREAD

**Issue by emiljoha** [BobbyAnguelov/NeuralNetwork#1]
Hi, 

Read [tutorial](https://takinginitiative.wordpress.com/2008/04/23/basic-neural-network-tutorial-c-implementation-and-source-code/) and liked it very much. Thank you! 

But problems arose when starting to look into the code. Tried to compile it with g++ and it gave lots of warnings and finally failed to compile. (can post output if needed). Notably that the main function returned void instead of int and use of variable-length array types. After researching these warnings a common theme became evident. They where c-standard... 

So what standard is this "c++" code intended to follow?

**Comment by BobbyAnguelov** [comment]
To be honest, this is code I wrote nearly a decade ago when I was starting to get into c++ so it's not following any standard. It's probably some sort of vc6 / c99 /  pre c±±11 hybrid abortion. 

It definitely needs some love and is not meant for use as is but rather as a reference. I only put it up here as it is easier for people to access rather than some zip file.

**Comment by emiljoha** [comment]
Ok, that clears it up. But maybe put this "disclaimer" in [READEM.md](README.md) and/or on the [website](https://takinginitiative.wordpress.com/2008/04/23/basic-neural-network-tutorial-c-implementation-and-source-code/) ?
